;(function() {

        job_info = [
{ id:'model1', cluster_kb:'1', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'1' } ,
{ id:'model2', cluster_kb:'1', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model3', cluster_kb:'1', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model4', cluster_kb:'1', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'2' } ,
{ id:'model5', cluster_kb:'1', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model6', cluster_kb:'1', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model7', cluster_kb:'1', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'3' } ,
{ id:'model8', cluster_kb:'2', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model9', cluster_kb:'2', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model10', cluster_kb:'2', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'3' } ,
{ id:'model11', cluster_kb:'2', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model12', cluster_kb:'2', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'3' } ,
{ id:'model13', cluster_kb:'2', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model14', cluster_kb:'2', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'3' } ,
{ id:'model15', cluster_kb:'3', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'3' } ,
{ id:'model16', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'2' } ,
{ id:'model17', cluster_kb:'3', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model18', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'2' } ,
{ id:'model19', cluster_kb:'3', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model20', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model21', cluster_kb:'3', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model22', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model23', cluster_kb:'3', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'1' } ,
{ id:'model24', cluster_kb:'3', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'1' } ,
{ id:'model25', cluster_kb:'3', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'1' } ,
{ id:'model26', cluster_kb:'3', group_no:'1', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'1' } ,
{ id:'model27', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'1' } ,
{ id:'model28', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'1' } ,
{ id:'model29', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'1' } ,
{ id:'model30', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model31', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'1' } ,
{ id:'model32', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model33', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'1' } ,
{ id:'model34', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model35', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model36', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model37', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model38', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model39', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
{ id:'model40', cluster_kb:'3', group_no:'0', boot_process:'JobModel', boot_params:'-w=hoge', boot_flg:'1', exec_flg:'0' } ,
        ];
})();
