;(function() {

    // 接続関係リスト
        jobwait = [
{ next:'model26' , pre:'model21' },
{ next:'model24' , pre:'model6' },
{ next:'model38' , pre:'model34' },
{ next:'model39' , pre:'model11' },
{ next:'model10' , pre:'model5' },
{ next:'model19' , pre:'model27' },
{ next:'model22' , pre:'model10' },
{ next:'model19' , pre:'model16' },
{ next:'model26' , pre:'model25' },
{ next:'model33' , pre:'model23' },
{ next:'model17' , pre:'model23' },
{ next:'model2' , pre:'model14' },
{ next:'model12' , pre:'model33' },
{ next:'model28' , pre:'model18' },
{ next:'model40' , pre:'model9' },
{ next:'model8' , pre:'model7' },
{ next:'model39' , pre:'model15' },
{ next:'model33' , pre:'model8' },
{ next:'model19' , pre:'model21' },
{ next:'model13' , pre:'model28' },
{ next:'model13' , pre:'model15' },
{ next:'model39' , pre:'model8' },
{ next:'model19' , pre:'model21' },
{ next:'model27' , pre:'model28' },
{ next:'model12' , pre:'model5' },
{ next:'model37' , pre:'model20' },
{ next:'model34' , pre:'model36' },
{ next:'model37' , pre:'model34' },
{ next:'model25' , pre:'model31' },
{ next:'model30' , pre:'model16' },
{ next:'model8' , pre:'model18' },
{ next:'model28' , pre:'model29' },
{ next:'model19' , pre:'model35' },
        ];   

})();
